-- ============================================================================
-- ARCHITECREATURE HUNT — stations seed data
-- ============================================================================
-- Auto-generated from the STATIONS[] array in ScavengerHuntPrototype.jsx.
-- Do not hand-edit the content here — regenerate from the .jsx source any
-- time station copy changes, so the two never drift apart (per handoff doc).
--
-- Safe to re-run: upserts by id, so running this twice (or after a content
-- tweak) won't create duplicates or fail. Run after architecreature_hunt_schema.sql.
-- ============================================================================

insert into stations (
  id,
  name,
  act,
  judging,
  letter,
  badge,
  character,
  meet_line,
  greeting,
  history,
  challenge_text,
  fact_log,
  moral,
  farewell,
  next_area,
  next_clue_hint,
  creature,
  is_real_creature,
  bridge_quote_1,
  bridge_quote_2,
  sort_order
)
values
  (1, 'Plaça Nova — BARCINO', 1, 'staff', 'G', null, 'Emperor Augustus', 'speaking from atop the old Roman gate', 'Stand still, traveler. Two thousand years and you still don''t recognize an Emperor when you see one. I built this city''s bones — BARCINO, gate, walls, and all. Show me you understand what stone like this is worth.', 'These four columns and this gate are real Roman remains. The settlement was founded in the 1st century BC as a Roman colony named BARCINO — small, fortified, and deliberately placed for trade and defense. The seed everything else in this city grew from.', 'Spell out B-A-R-C-I-N-O using only your group''s bodies, lying flat on the ground. Get the angle right and have someone photograph the whole thing from directly above.', 'BARCINO was founded by the Romans in the 1st century BC as a fortified trading colony — the seed of modern Barcelona.', 'Solid Foundations', 'Good. Now you understand: nothing in this city stands without a foundation laid first. Take this — your first letter, G. Hold onto it, and every letter like it you earn from here on. Somewhere in this old quarter stand six arches, easy to walk past without ever noticing. Six arches, six letters, one word waiting to be spelled — but you won''t know which order until you''ve earned the right to ask. Walk on — the dead have something to tell you, not far from here.', 'the Roman Necropolis', 'Look for a sunken stone courtyard, fenced off below street level, visible through glass panels in the pavement.', null, null, null, null, 1),
  (2, 'Roman Necropolis', 1, 'auto', 'R', 'Quiet Mind', 'A dead Roman poet', 'speaks from the sunken tombs', 'Down here it''s quiet. Has been for about two thousand years. I used to write — verses nobody important enough to remember. Funny thing about dying: you start wishing someone had asked your name.', 'This sunken courtyard is a real Roman necropolis — burials were kept just outside the city walls, as Roman law required. Most of the names on these stones were never grand: soldiers, merchants, freed slaves. The unremarkable many, who built the city just as much as any Emperor.', 'Choose one of the unnamed graves. Invent a name and a one-line story for whoever lies there — who they were, what they wanted, what they left behind.', 'This sunken courtyard is a real Roman necropolis, where ordinary citizens — not emperors — were buried just outside the city walls.', 'Respect', 'Good story. Whoever they were, you gave them a name today — that''s more than most people get. That''s your second letter, R, to add to the first. Climb back up into the light. The Queen is waiting, and she doesn''t like to be kept.', 'Plaça del Rei', 'Look for a wide open square framed by an old palace facade and a long, fan-shaped stone staircase.', null, null, null, null, 2),
  (3, 'Plaça del Rei', 1, 'staff', 'A', null, 'Isabel la Católica', 'standing at the top of the great stone staircase', 'Do you know whose feet have climbed these steps? Mine, for one — Columbus knelt right where you''re standing, back from a voyage that changed how every map in this city was drawn. Show me your group can command a room the way I once did.', 'Plaça del Rei was the ceremonial heart of the Kingdom of Aragon. Tradition holds that Christopher Columbus was received here by Ferdinand and Isabella after his first voyage in 1493, on this very staircase.', 'One member of your group becomes the monarch on the top step. The rest of the group must deliver a one-minute royal proclamation to them, in character, without laughing.', 'Plaça del Rei''s grand staircase is where tradition says Columbus was received by the Catholic Monarchs after his first voyage in 1493.', 'Presence', 'Decreed and accepted. That''s your third letter, A. Now look around you — six arches, right here in this square, though you''ve only carried letters for three of them so far. Their count isn''t an accident. Go now, and find the turtle who''s seen every visitor to this square and judged most of them unworthy.', 'Casa de l''Ardiaca', 'Look for a small carved stone turtle set into the wall beside an old wooden mailbox slot.', null, null, null, null, 3),
  (4, 'Casa de l''Ardiaca', 1, 'staff', 'N', null, 'The Turtle', 'carved into the wall, holding up a mailbox that hasn''t moved in a century', 'Slow down. Everyone rushes past me like I''m furniture. I''ve held this mailbox since before your grandparents were born, and I am in absolutely no hurry to talk to you.', 'Casa de l''Ardiaca''s courtyard mailbox is topped by a small bronze turtle and swallows, added during a 1902 renovation — a quiet bit of whimsy on a building that''s been rebuilt many times since the 12th century.', 'Move as a group at turtle speed — single file, hands on the shoulders of the person ahead — from one side of the courtyard to the other, without anyone breaking contact or stepping out of rhythm.', 'The bronze turtle and swallows on Casa de l''Ardiaca''s mailbox were added in a 1902 renovation of a building with roots in the 12th century.', 'Patience', 'Slowly, but you got there. That''s your letter, N. Go on now — there''s a buried street under El Born nobody''s drawn a map of in a long time.', 'El Born', 'Look for a long market hall with a glass roof held up by iron columns and arches.', null, null, null, null, 4),
  (5, 'El Born', 1, 'staff', 'D', null, 'An unknown architect', 'pointing down at the excavated street beneath the market floor', 'Nobody remembers my name, and that''s the joke of this whole profession — you build the thing, and the city remembers the building, never you. Look down. That street was somebody''s whole life''s work too.', 'El Born''s market hall was built in 1876; archaeological excavations beneath it later uncovered an entire intact street from the 1700s, destroyed in the Bourbon siege of 1714 — now preserved under glass.', 'Look down through the glass at the excavated street below. Sketch, from memory, what you think that street looked like full of people, on the back of any paper you have, or describe it aloud to the group.', 'Beneath El Born''s 1876 market hall lies an excavated 18th-century street, destroyed in the 1714 siege and preserved under glass.', 'Forgotten Builders', 'Not bad, for someone who never met me. That''s your letter, O. I may be forgotten, but I came first — every arch and facade you''ll meet from here owes something to streets like mine. Go carry some weight for once — there are dock-porters nearby who''d like a word.', 'Santa Maria del Mar', 'Look for a church with tall, plain stone walls and twin octagonal bell towers rising above the rooftops.', null, null, null, null, 5),
  (6, 'Santa Maria del Mar — The Bastaixos', 1, 'staff', 'O', 'Strong Backs', 'A Bastaix (dock-porter)', 'standing beside the carved wooden door, mid-stride, forever carrying a stone', 'You see this church? My back built it. Every stone came from the beach at La Ribera, half a mile away, carried here on the shoulders of men like me — for free, because we believed in it. Show me you understand what that kind of weight feels like.', 'The Bastaixos were dock-porters who, between 1329 and 1383, carried every stone for Santa Maria del Mar from the beach to this site on their backs, unpaid, as an act of devotion. They''re honored in the carving on the very door beside you.', 'Piggyback relay: one person carries another on their back across the square and back. Switch carriers, and complete the relay as a full group before time runs out.', 'The Bastaixos, medieval dock-porters, carried every stone for Santa Maria del Mar from the beach on their own backs between 1329 and 1383.', 'Sacrifice', 'Now you''ve felt a fraction of that weight. That''s your letter, D. Six letters, all collected — out of order, the way history usually arrives. There''s a bridge ahead, and somebody on it who''s been waiting a long time to ask you a question. Go carefully.', 'Pont del Bisbe', 'Look for a covered stone bridge — and a skull and dagger carved into the stonework beneath it.', null, null, null, null, 6),
  (7, 'Pont del Bisbe', 1, 'bridge', null, 'Dead-Eye', 'The Watcher', 'leaning against the bridge, eyes on the skull carved into the stone', 'Six letters, no word. That''s the state I find most people in — plenty of pieces, no idea what they spell. See that skull and dagger under the bridge? Local legend says touch the skull or step on it and you''re cursed. I wouldn''t risk it. First — show me you can hit a target blind.', 'The Gothic bridge connecting the Palau de la Generalitat to the Casa de l''Ardiaca was added in 1928, designed to look medieval. The skull-and-dagger carving beneath it is real, and the legend about touching it is older than the bridge itself.', 'Blindfolded, one at a time, each member of your group tries to pin a tail (or sticker) onto a target taped to a wall. The group gets three attempts total to land at least one hit.', 'Pont del Bisbe was built in 1928 to look medieval. The skull-and-dagger carving beneath it is genuinely old, and so is the curse legend attached to it.', 'Trusting Your Aim', 'Go on. Rest first if you need to — what''s coming will ask more of you than letters and arches did.', 'a quiet pause before the real hunt begins', null, null, null, 'Not bad, blind. Now — six letters. G, R, A, N, D, O. One word. Arrange them in the right order, and I''ll tell you what''s actually happening in this city.', '...DRAGON. Good. You got there. Something''s been loose in this city for longer than anyone wants to admit — wearing different faces in different corners of it. Find it, and you''ll understand what these stones have been trying to tell you all along. Go carefully — not everything that looks like the answer is the answer.', 7),
  (8, 'Sant Felip Neri', 2, 'staff', null, null, 'The Watcher', 'standing very still in the small square, listening', 'Quiet, for a second. Did you hear that, a minute ago? Sounded almost like a roar. I think it came from over toward the Palau. Before you go — look at these walls. They''re not decoration.', 'The pockmarks across this church''s facade are real shrapnel scars from a bombing on January 30, 1938, during the Spanish Civil War, which killed dozens of people, many of them children sheltering in the square.', 'In silence, run your hand once over the scarred wall. Then, as a group, sit for thirty full seconds without speaking, before moving on.', 'The pockmarked walls of Sant Felip Neri are shrapnel scars from a 1938 bombing during the Spanish Civil War.', 'Memory', 'That roar I heard — I''d put money on it being something dragon-shaped, over by the Palau. Go look. Carefully.', 'Palau Güell', 'Look for a wrought-iron gate beneath a tall stone facade, with something perched above it.', null, null, null, null, 8),
  (9, 'Palau Güell', 2, 'dragon', null, null, 'The Bird of Palau Güell', 'perched above the gate, unimpressed by the attention', 'I''ve been mistaken for a dragon more times than I can count, and every single time it''s been embarrassing for whoever made the mistake. I''m a bird. Look at me. I have a beak.', 'Palau Güell was designed by a young Antoni Gaudí between 1886 and 1890 as a private mansion for his patron Eusebi Güell. Its rooftop is covered in surreal mosaic-tiled chimneys, and ironwork creatures perch above its entrance — easy to mistake for something fiercer than they are, from a distance.', 'Take your group photo with the bird above the gate, then find and photograph at least two of the chimney shapes on the rooftop terrace photo provided — match each to what it resembles.', 'Palau Güell (1886–1890) was Antoni Gaudí''s first major Barcelona commission, built for his patron Eusebi Güell — its ironwork and chimneys are easy to mistake for something else at a glance.', 'Not Everything That Looks Fierce Is', 'Try the Rambla. There''s a dragon down there that''s been fooling tourists for over a century — much better at it than I ever was.', 'La Rambla — the Mosaic and the Dragon', 'Look for a colorful circular mosaic set into the pavement, and a dragon holding an umbrella on a nearby building corner.', 'The Bird of Palau Güell', false, null, null, 9),
  (10, 'La Rambla — the Mosaic and the Dragon', 2, 'dragon', null, null, 'The Umbrella Dragon', 'perched on the corner of an old shop, holding an umbrella, as it has for over a century', 'Yes, I''m a dragon. Yes, I''m holding an umbrella. No, I am not the one you''re hunting — I''ve just been advertising parasols since 1885 and I''m very good at my job. Step on the mosaic behind you while you''re here; everyone does.', 'This dragon-and-umbrella sculpture has marked an old umbrella and parasol shop on La Rambla since 1885. A few steps away, Joan Miró set a large circular mosaic into the pavement itself in 1976, marking the heart of the street he grew up walking.', 'Stand in the center of Miró''s mosaic. As a group, name three colors you see in it, then take a photo standing on it with the dragon visible in the background.', 'The umbrella-shop dragon on La Rambla dates to 1885; Joan Miró''s pavement mosaic nearby was installed in 1976.', 'Spectacle Isn''t Substance', 'If you''re hunting something real, try the market with the wild roof. Things hide in plain colorful sight there too.', 'Mercat Santa Caterina', 'Look for a wavy, multicolored mosaic roof rising above a row of market stalls.', 'The Umbrella Dragon', false, null, null, 10),
  (11, 'Mercat Santa Caterina', 2, 'staff', null, null, 'Mariona, the Fruit Seller', 'behind a stall stacked with produce in every color of that roof above her', 'Third generation, this stall. My grandmother sold here before this roof existed — back when the market was plainer, and so, frankly, was the gossip. You want a dragon? I sell better colors than any dragon ever wore. Prove you''ve actually looked at them.', 'Mercat Santa Caterina has stood on this site since 1848, built over the ruins of a medieval convent destroyed in 1835. Its wave-shaped, multicolored mosaic roof was added in a 2005 renovation by architects Enric Miralles and Benedetta Tagliabue, echoing the produce sold beneath it.', 'Photograph produce in five different colors around the market, then use those exact colors to paint your group as a mosaic portrait, pixel by pixel.', 'Mercat Santa Caterina''s wave-shaped 2005 roof, by Enric Miralles and Benedetta Tagliabue, was designed to echo the colors of the produce sold inside.', 'Color Tells a True Story Too', 'No dragons here, just good fruit. But I''ll tell you — if I were hiding something, I''d hide it somewhere loud and beautiful, like that concert hall uptown. Go ask the man with the temper about music.', 'Palau de la Música Catalana', 'Look for an ornate stained-glass and mosaic facade on a narrow street, unmistakably more decorated than its neighbors.', null, null, null, null, 11),
  (12, 'Palau de la Música Catalana', 2, 'staff', null, null, 'Beethoven', 'carved in stone above the facade, glowering down at passersby', 'I never set foot in this city, and they put my face on this building anyway. I suppose that''s what happens when an orchestra venerates you. Don''t waste my afterlife — prove you can make a sound worth hearing.', 'Palau de la Música Catalana, built between 1905 and 1908 by Lluís Domènech i Montaner, is covered in mosaics, stained glass, and sculpture — including a bust of Beethoven, honoring the European composers the Orfeó Català choir championed.', 'As a full group, sing one verse of any song together, loudly enough that strangers nearby can hear it. No instruments allowed.', 'Palau de la Música Catalana (1905–1908), designed by Lluís Domènech i Montaner, honors composers like Beethoven in its sculpture despite his having no direct tie to Barcelona.', 'Full Chorus', '...Acceptable. Now go. There''s an arch up near the old Exposition grounds covered in carved figures — one more architect this city owes credit to, and one more creature worth a closer look before you finish this.', 'the Arc de Triomf', 'Look for a tall freestanding brick arch spanning a wide avenue, covered in carved figures and shields.', null, null, null, null, 12),
  (13, 'Arc de Triomf', 2, 'staff', null, null, 'The Winged Figure of the Arch', 'carved into the brickwork above you, wings spread, easy to miss if you don''t look up', 'Everyone walks under me and looks at the arch. Nobody looks at me. I''ve been holding this corner up, decoratively speaking, since this whole avenue was built for a party that lasted six months and never came back.', 'The Arc de Triomf was designed by Josep Vilaseca i Casanovas as the grand entrance to the 1888 Barcelona Universal Exposition. Its brick and sculptural reliefs — by several different sculptors — depict Barcelona welcoming visiting nations, along with shields, allegorical figures, and winged creatures worked into the ornamentation.', 'Find one carved winged or animal figure on the arch besides the main reliefs. Photograph it, and as a group, guess out loud what it''s doing there before reading the plaque (if there is one).', 'The Arc de Triomf (1888) was designed by Josep Vilaseca i Casanovas as the entrance to that year''s Barcelona Universal Exposition.', 'Look Up Once in a While', 'Go on, then. Last stop. Whatever you''ve been hunting, it isn''t hiding in brickwork anymore — it''s standing in the open, back where this whole thing started.', 'Plaça Sant Jaume — the Finale', 'Look for the carved skull beneath the bridge you crossed earlier — you''re going back the way you came.', null, null, null, null, 13),
  (14, 'Plaça Sant Jaume — The Finale', 2, 'finale', null, null, 'The Watcher', 'waiting exactly where the bridge first sent you off', 'You''re back. Good — that means you found nothing, four times over, and didn''t settle for any of it. A bird. An umbrella. A roof full of fruit. A wing in the brickwork. None of them were it, and you knew that, and kept going anyway. Look up.', 'Sant Jordi (Saint George) is Catalonia''s patron saint, honored every April 23rd — Barcelona''s biggest celebration of books and roses — for slaying a dragon to save a princess. Versions of that dragon are carved, painted, or tiled onto buildings all across this city, including several within sight of where you''re standing right now.', 'Find a real carved or sculpted Sant Jordi dragon within sight of this square. Photograph your whole group with it, and explain in one sentence why this one — and not the bird, the umbrella, the roof, or the wing — is the one you were sent to find.', 'Sant Jordi, Catalonia''s patron saint, is honored every April 23rd for slaying a dragon — versions of which are carved across many buildings in this part of the city.', 'Discernment', 'There it is. Not loud, not hiding, not pretending to be anything else — just old stone, doing what it''s always done, waiting for someone to actually look. That''s the whole hunt, in the end. Well done.', null, null, 'Sant Jordi''s Dragon', true, null, null, 14)
on conflict (id) do update set
  name = excluded.name,
  act = excluded.act,
  judging = excluded.judging,
  letter = excluded.letter,
  badge = excluded.badge,
  character = excluded.character,
  meet_line = excluded.meet_line,
  greeting = excluded.greeting,
  history = excluded.history,
  challenge_text = excluded.challenge_text,
  fact_log = excluded.fact_log,
  moral = excluded.moral,
  farewell = excluded.farewell,
  next_area = excluded.next_area,
  next_clue_hint = excluded.next_clue_hint,
  creature = excluded.creature,
  is_real_creature = excluded.is_real_creature,
  bridge_quote_1 = excluded.bridge_quote_1,
  bridge_quote_2 = excluded.bridge_quote_2,
  sort_order = excluded.sort_order,
  updated_at = now();
